# Generated by Django 4.2.28 on 2026-02-17 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0011_module_has_assignment_module_has_quiz'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1)),
                ('avg_engagement', models.FloatField(default=0.0)),
                ('avg_quiz_score', models.FloatField(default=0.0)),
                ('avg_assignment_score', models.FloatField(default=0.0)),
                ('learning_health_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('excellent', 'Excellent'), ('improving', 'Improving'), ('needs_attention', 'Needs Attention')], default='needs_attention', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_health', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week'],
            },
        ),
        migrations.CreateModel(
            name='VideoEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_watch_time', models.FloatField(default=0.0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('seek_count', models.PositiveIntegerField(default=0)),
                ('playback_rate_avg', models.FloatField(default=1.0)),
                ('focus_loss_seconds', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'module'], name='analytics_v_user_id_be7055_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
