# Generated by Django 4.2.28 on 2026-02-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_module_ai_generated_data_module_has_assignment_and_more'),
        ('assignments', '0005_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(blank=True, help_text='Submitted assignment content'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_questions', to='modules.module')),
            ],
        ),
    ]
