# Generated by Django 5.2.11 on 2026-02-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_module_assignment_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to the module video (YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
    ]
