# Generated by Django 4.2.28 on 2026-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_module_has_assignment_module_has_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='ai_generated_data',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='module',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='module',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
