# Generated by Django 4.2.28 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_module_ai_generated_data_module_has_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='has_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='has_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
