# Generated by Django 4.2.28 on 2026-02-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_module_has_assignment_module_has_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
    ]
