# Generated by Django 4.2.28 on 2026-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_module_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='video_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('youtube', 'YouTube')], default='upload', max_length=20),
        ),
    ]
