# Generated by Django 4.2.28 on 2026-02-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0013_module_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
