# Generated by Django 4.2.28 on 2026-02-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0013_module_video_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_percent', models.FloatField(default=0)),
                ('quiz_percent', models.FloatField(default=0)),
                ('assignment_percent', models.FloatField(default=0)),
                ('is_video_completed', models.BooleanField(default=False)),
                ('is_quiz_completed', models.BooleanField(default=False)),
                ('is_assignment_completed', models.BooleanField(default=False)),
                ('module_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'module'], name='learner_pro_user_id_8597dd_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
